[project]
name = "jbnu-qwen3-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.8.1",
    "torch>=2.7.1",
    "transformers>=4.53.1",
]
